Additions to .bashrc

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -12,10 +12,46 @@
 
 test -s ~/.alias && . ~/.alias || true
 
-if [[ -f ${HOME}/.config/shell/functions/bash_functions.sh ]]; then
-    source ${HOME}/.config/shell/functions/bash_functions.sh
+# Enable ssh-agent to share SSH_AUTH_SOCK with subshells. Helps with "chezmoi cd" command.
+export SSH_AUTH_SOCK="$HOME/.ssh/ssh-agent.sock"
+if ! pgrep -u "$USER" ssh-agent > /dev/null; then
+    rm -f "$SSH_AUTH_SOCK"
+    ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
 fi
 
-if [[ -f ${HOME}/.config/shell/aliases/common_aliases ]]; then
-    . ${HOME}/.config/shell/aliases/common_aliases 
+# Import custom functions into the session
+if [[ -f ${HOME}/.config/shell/functions/bash_functions.sh ]]; then
+  source ${HOME}/.config/shell/functions/bash_functions.sh
 fi
+
+# Import aliases into the session
+if [[ -f ${HOME}/.config/shell/aliases/common_aliases ]]; then
+  . ${HOME}/.config/shell/aliases/common_aliases 
+fi
+
+# Get status of the last command to use in the shell prompt
+exitstatus()
+{
+if [[ $? == 0 ]]; then
+printf "\033[01;32m""\xE2\x9C\x93"
+else
+printf "\033[01;31m""\xE2\x9C\x98"
+fi
+}
+
+# Set the shell prompt
+PS1='\n$(exitstatus) \[\e[01;32m\]\u\[\e[01;36m\]@\[\e[01;34m\]\h \[\e[01;36m\](\[\e[01;33m\]\w\[\e[01;36m\])\n\[\e[00;37m\]\$ \[\e[00m\]'
+
+# If not running interactively, don't do anything
+# or else WinSCP will fail to connect.
+[[ $- != *i* ]] && return
+
+# Auto-attach tmux "Default" session
+if [[ -z "$TMUX" ]]; then
+  if tmux has-session -t Default 2>/dev/null; then
+    exec tmux attach-session -t Default
+  else
+    exec tmux new-session -s Default
+  fi
+fi
+
